print("sana")
print(2+3)
print("we are learning in codanics platform")
print(2+4*72_5)
print("hello world")
print(4/6)
print(87*2_7+6)
print("my first program")
print("2@*7")
print("3$*5@")
print("first line of code")
